
package com.github.somi92.hsms.webservice.provider;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HSMSProviderService", targetNamespace = "http://provider.webservice.hsms.somi92.github.com/", wsdlLocation = "http://localhost:8080/ws/hsms/service?wsdl")
public class HSMSProviderService
    extends Service
{

    private final static URL HSMSPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException HSMSPROVIDERSERVICE_EXCEPTION;
    private final static QName HSMSPROVIDERSERVICE_QNAME = new QName("http://provider.webservice.hsms.somi92.github.com/", "HSMSProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/hsms/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HSMSPROVIDERSERVICE_WSDL_LOCATION = url;
        HSMSPROVIDERSERVICE_EXCEPTION = e;
    }

    public HSMSProviderService() {
        super(__getWsdlLocation(), HSMSPROVIDERSERVICE_QNAME);
    }

    public HSMSProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HSMSPROVIDERSERVICE_QNAME, features);
    }

    public HSMSProviderService(URL wsdlLocation) {
        super(wsdlLocation, HSMSPROVIDERSERVICE_QNAME);
    }

    public HSMSProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HSMSPROVIDERSERVICE_QNAME, features);
    }

    public HSMSProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HSMSProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HSMSService
     */
    @WebEndpoint(name = "HSMSProviderPort")
    public HSMSService getHSMSProviderPort() {
        return super.getPort(new QName("http://provider.webservice.hsms.somi92.github.com/", "HSMSProviderPort"), HSMSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HSMSService
     */
    @WebEndpoint(name = "HSMSProviderPort")
    public HSMSService getHSMSProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://provider.webservice.hsms.somi92.github.com/", "HSMSProviderPort"), HSMSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HSMSPROVIDERSERVICE_EXCEPTION!= null) {
            throw HSMSPROVIDERSERVICE_EXCEPTION;
        }
        return HSMSPROVIDERSERVICE_WSDL_LOCATION;
    }

}
