
package com.github.somi92.hsms.webservice.provider;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HSMSService", targetNamespace = "http://provider.webservice.hsms.somi92.github.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HSMSService {


    /**
     * 
     * @return
     *     returns java.util.List<com.github.somi92.hsms.webservice.provider.Hsms>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllActions", targetNamespace = "http://provider.webservice.hsms.somi92.github.com/", className = "com.github.somi92.hsms.webservice.provider.GetAllActions")
    @ResponseWrapper(localName = "getAllActionsResponse", targetNamespace = "http://provider.webservice.hsms.somi92.github.com/", className = "com.github.somi92.hsms.webservice.provider.GetAllActionsResponse")
    @Action(input = "http://provider.webservice.hsms.somi92.github.com/HSMSService/getAllActionsRequest", output = "http://provider.webservice.hsms.somi92.github.com/HSMSService/getAllActionsResponse")
    public List<Hsms> getAllActions();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.github.somi92.hsms.webservice.provider.Hsms>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActionsByPriority", targetNamespace = "http://provider.webservice.hsms.somi92.github.com/", className = "com.github.somi92.hsms.webservice.provider.GetActionsByPriority")
    @ResponseWrapper(localName = "getActionsByPriorityResponse", targetNamespace = "http://provider.webservice.hsms.somi92.github.com/", className = "com.github.somi92.hsms.webservice.provider.GetActionsByPriorityResponse")
    @Action(input = "http://provider.webservice.hsms.somi92.github.com/HSMSService/getActionsByPriorityRequest", output = "http://provider.webservice.hsms.somi92.github.com/HSMSService/getActionsByPriorityResponse")
    public List<Hsms> getActionsByPriority(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
